Allow to flatten `IgnoredAny`
serde-rs/serde pull request #2436
Opened 2023-04-29 21:04 UTC by Mingun

This can be useful for use-case described in #2432 (if other problems will be solved) and if you have a generic struct with flatten field and want to pass an `IgnoredAny` for whatever reason.

I also implement `PartialEq` for `IgnoredAny` so it can be tested using `assert_de_tokens`.

2023-05-05 01:28 UTC, dtolnay requested changes
Independent of #2437, I am not sure whether this still has a use case. Could you let me know whether this PR is still needed?

For deserializing struct containing flattened fields from a map, I expect people would not need to write `#[serde(flatten)] inner: IgnoredAny` because ignoring all other fields is already the default behavior.

Thanks anyway for the PR!

2023-05-05 16:18 UTC, dtolnay commented
Do we know of any code that uses or has wanted to use `flatten` in that manner with a generic type?

In general "least astonishment" is not compelling to me as it's in tension with "least bloat" and the intersection between features can be disproportionately costly to support for the sake of something that literally nobody might want in the first place.

2023-05-06 17:10 UTC, Mingun commented
The point is not whether we know or not. I believe that the library should not limit the user to strange, not explained restrictions.

> can be disproportionately costly to support 

I think, that here definitely not this case. In fact, this PR _decreases_ cost for support, because it removes special case and adds an explicit test for it. In contrast, in current situation you actually supports invariant that `IgnoredAny` cannot be type of the `#[serde(flatten)]` field, but you do that without a test that check that this invariant is hold.

2023-07-06 23:35 UTC, dtolnay approved these changes
Sounds good. Thanks for the PR!

2023-07-06 23:35 UTC, merged